/*
CREATE DATABASE Mundial;
*/
USE Mundial;
GO

IF OBJECT_ID('Usuario') IS NOT NULL DROP TABLE Usuario; 
CREATE TABLE Usuario(
	UsuarioId INT IDENTITY(1,1),
	Nombre VARCHAR(30),
	Clave VARCHAR(30),
	Tipo VARCHAR(30)

	CONSTRAINT PK_Usuario_01 PRIMARY KEY(UsuarioId)
)
GO

IF OBJECT_ID('Posicion') IS NOT NULL DROP TABLE Posicion;
CREATE TABLE Posicion(
	PosicionId INT IDENTITY(1,1),
	Nombre VARCHAR(30)

	CONSTRAINT PK_Posicion_01 PRIMARY KEY(PosicionId)
)
GO

IF OBJECT_ID('Equipo') IS NOT NULL DROP TABLE Equipo;
CREATE TABLE Equipo(
	EquipoId INT IDENTITY(1,1),
	Nombre VARCHAR(30) UNIQUE,
	Participaciones INT

	CONSTRAINT PK_Equipo_01 PRIMARY KEY(EquipoId)
)
GO

IF OBJECT_ID('Jugador') IS NOT NULL DROP TABLE Jugador;
CREATE TABLE Jugador(
	JugadorId INT IDENTITY(1,1),
	Nombre VARCHAR(30),
	Apellido VARCHAR(30),
	FechaNacimiento DATE,
	Estatura DECIMAL(3,2)

	CONSTRAINT PK_Jugador_01 PRIMARY KEY(JugadorId),

	PosicionId INT FOREIGN KEY REFERENCES Posicion(PosicionId),
	EquipoId INT FOREIGN KEY REFERENCES Equipo(EquipoId)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)
GO

IF OBJECT_ID('Goleador') IS NOT NULL DROP TABLE Goleador;
CREATE TABLE Goleador(
	GoleadorId INT IDENTITY(1,1),
	Goles INT,

	CONSTRAINT PK_Goleador_01 PRIMARY KEY(GoleadorId),

	JugadorId INT FOREIGN KEY REFERENCES Jugador(JugadorId)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)
GO

IF OBJECT_ID('Resultado') IS NOT NULL DROP TABLE Resultado;
CREATE TABLE Resultado(
	ResultadoId INT IDENTITY(1,1),
	GolesaFavor VARCHAR(30),
	GolesenContra VARCHAR(30),
	NumeroPartido INT,

	CONSTRAINT PK_Resultado_01 PRIMARY KEY(ResultadoId),

	EquipoId INT FOREIGN KEY REFERENCES Equipo(EquipoId)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)
GO

IF OBJECT_ID('Asistencia') IS NOT NULL DROP TABLE Asistencia;
CREATE TABLE Asistencia(
	AsistenciaId INT IDENTITY(1,1),
	Asistencias INT,

	CONSTRAINT PK_Asistencia_01 PRIMARY KEY(AsistenciaId),

	JugadorId INT FOREIGN KEY REFERENCES Jugador(JugadorId)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)
GO

IF OBJECT_ID('TarjetaRoja') IS NOT NULL DROP TABLE TarjetaRoja;
CREATE TABLE TarjetaRoja(
	TarjetaRojaId INT IDENTITY(1,1),
	Numero INT,

	CONSTRAINT PK_TarjetaRoja_01 PRIMARY KEY(TarjetaRojaId),

	JugadorId INT FOREIGN KEY REFERENCES Jugador(JugadorId)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)
GO

IF OBJECT_ID('TablaPosicion') IS NOT NULL DROP TABLE TablaPosicion;
CREATE TABLE TablaPosicion(
	TablaPosicionId INT IDENTITY(1,1),
	PJ INT,
	PE INT,
	PP INT,
	GF INT,
	GC INT,

	CONSTRAINT PK_TablaPosicion_01 PRIMARY KEY(TablaPosicionId),

	EquipoId INT FOREIGN KEY REFERENCES Equipo(EquipoId)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)